version: '3.8'

services:

  db:
    image: postgres:14.8
    environment:
      POSTGRES_DB: outbox-demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5444:5432"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_PASS: "123456"
      RABBITMQ_DEFAULT_USER: "outbox"
    ports:
      - "56720:5672"
      - "8081:15672"

networks:
  default: