services:

  app:
    image: outbox-demo
    container_name: outbox-demo-app
    restart: on-failure
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["./app"]

  relay:
    image: outbox-demo
    container_name: outbox-demo-relay
    restart: on-failure
    build:
      context: .
    env_file:
      - .env
    command: [ "./relay" ]

  worker:
    image: outbox-demo
    container_name: outbox-demo-worker
    restart: on-failure
    build:
      context: .
    env_file:
      - .env
    command: [ "./worker" ]

networks:
  outbox: